### ISSUE TITLE
update look of discover page to fit the rest

### ISSUE THREAD

**Issue by sa8** [kinbaApp/medusa-kinba#21]
Kind of started this!

Ideally we want to have something that looks nicer than a list of public key.

**Comment by batoulalkarim** [comment]
I've created a reusable 'DiscoverSuggestion" component so that we can have a less bulky option for displaying creators. All I really did to that component is reduce the height, I think the creators should be displayed as a banner of some sort for scaling purposes, and I can implement that quickly, so it's up to you!
